name: Publish All
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Graphviz and Spin
        run: sudo apt install graphviz spin
      - name: Install TeXLive
        run: sudo apt install texlive-base texlive-fonts-extra texlive-humanities texlive-lang-cyrillic texlive-lang-english texlive-lang-german texlive-latex-extra texlive-latex-recommended texlive-latex-recommended texlive-luatex texlive-pictures texlive-plain-generic texlive-publishers texlive-science
      - name: install additional latex-packages
        run: |
          mkdir -p setup/latex/darkmode-latex-package
          git clone https://github.com/Rdeisenroth/darkmode-latex-package.git setup/latex/darkmode-latex-package
          cd setup/latex/darkmode-latex-package
          l3build install
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        run: "pip install -f https://download.pytorch.org/whl/torch_stable.html -r sys/requirements.txt"
      - name: Build Documents
        run: ".github/build-documents.sh all"
      - name: Publish Documents
        if: github.repository == 'fdamken/summaries'
        run: ".github/publish-documents.sh"
        env:
          gh_user: ${{ secrets.PUBLISH_GH_USER }}
          gh_token: ${{ secrets.PUBLISH_GH_TOKEN }}
